#!/usr/bin/env python3

from scipy.optimize import fsolve
import numpy as np

#correction_method 3
# Define the system of equations
def equations(variables):
	p1, p2, x1, x2, y1, y2, m1, m2, n1, n2 = variables
    # Define your ten equations here
	eq1 = p1+p2-512
	eq2 = x1+x2-17664
	eq3 = y1+y2-6144
	eq4 = m1+m2-5632
	eq5 = n1+n2-5632
	eq6 = p2/2+y2+2*m2+n2-x2-0
	eq7 = (p1/(p1+x1+y1+m1+n1))**2*(x1/(p1+x1+y1+m1+n1))/(p2/2/(p2/2+y2+m2+n2))-0.02296
	eq8 = (y1/(p1+x1+y1+m1+n1))*(x1/(p1+x1+y1+m1+n1))/(y2/(p2/2+y2+m2+n2))-0.00198907
	eq9 = (m1/(p1+x1+y1+m1+n1))*(x1/(p1+x1+y1+m1+n1))**2/(m2/(p2/2+y2+m2+n2))-0.011705377
	eq10 = (n1/(p1+x1+y1+m1+n1))*(x1/(p1+x1+y1+m1+n1))/(n2/(p2/2+y2+m2+n2))-0.90424

	return [eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9, eq10]

# Initial guess
initial_guess = np.array([67, 61, 780, 14668, 26, 5510, 839, 4849, 2565, 48])

# Solve the system of equations
solution = fsolve(equations, initial_guess)

print("Solution:", solution)


