#!/bin/bash

#grep 'external pressure' OUTCAR | cut -c 26-34 > P_external.txt
grep 'total pressure' OUTCAR | cut -c 22-30 > P.txt
grep 'T' OSZICAR | cut -c 11-16 > T.txt
grep 'F' OSZICAR | cut -c 39-54 > F.txt  # F is not internal energy because it includes electronic entropy and does not include kinetic energy of ions, but it is the one we want to use when doing thermal intergration.
#grep 'InternalEnergy' OUTCAR.umd.dat | awk '{print $2}' > U.txt
#grep 'ElectronicEntropy' OUTCAR.umd.dat | awk '{print $2}' > TS.txt
#grep 'KineticEnergyIons' OUTCAR.umd.dat | awk '{print $2}' > EK.txt
#grep 'unknown' --no-group-separator -A2 XDATCAR | awk 'NR % 3 == 0' | awk '{print $1}' > V.txt

i=4000

cat << EOF > block.py
#!/usr/bin/python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyblock

# Set global font to Arial and increase label/tick sizes
#plt.rcParams['font.family'] = 'Arial'
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 14
plt.rcParams['ytick.labelsize'] = 14
plt.rcParams['lines.linewidth'] = 1.5

P = np.loadtxt("P.txt",skiprows=$i,max_rows=None)
data = pd.Series(P)
(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
data = pyblock.pd_utils.reblock_summary(reblock_data)
data.to_csv('./P_block.csv',sep = '\t')

T = np.loadtxt("T.txt",skiprows=$i,max_rows=None)
data = pd.Series(T)
(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
data = pyblock.pd_utils.reblock_summary(reblock_data)
data.to_csv('./T_block.csv',sep = '\t')

F = np.loadtxt("F.txt",skiprows=$i,max_rows=None)
data = pd.Series(F)
(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
data = pyblock.pd_utils.reblock_summary(reblock_data)
data.to_csv('./F_block.csv',sep = '\t')

#data = np.loadtxt("U.txt",skiprows=0,max_rows=None)
#data = pd.Series(data)
#(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
#data = pyblock.pd_utils.reblock_summary(reblock_data)
#data.to_csv('./U_block.csv',sep = '\t')

#data = np.loadtxt("TS.txt",skiprows=0,max_rows=None)
#data = pd.Series(data)
#(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
#data = pyblock.pd_utils.reblock_summary(reblock_data)
#data.to_csv('./TS_block.csv',sep = '\t')

#data = np.loadtxt("EK.txt",skiprows=0,max_rows=None)
#data = pd.Series(data)
#(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
#data = pyblock.pd_utils.reblock_summary(reblock_data)
#data.to_csv('./EK_block.csv',sep = '\t')

#data = np.loadtxt("V.txt",skiprows=$i,max_rows=None)
#data = pd.Series(data)
#(data_length, reblock_data, covariance) = pyblock.pd_utils.reblock(data)
#data = pyblock.pd_utils.reblock_summary(reblock_data)
#data.to_csv('./V_block.csv',sep = '\t')

# ---------- quick plot (added) ----------
fig, axes = plt.subplots(3, 1, figsize=(6, 8), sharex=True)

axes[0].plot(P); axes[0].set_ylabel('P (kbar)')
axes[1].plot(T); axes[1].set_ylabel('T (K)')
axes[2].plot(F); axes[2].set_ylabel('F (eV)'); axes[2].set_xlabel('Time step')

for ax in axes: ax.grid(True, ls='--', alpha=0.4)
fig.tight_layout()
fig.savefig('PTF_time_series.pdf', dpi=450)
plt.show()

EOF

chmod 755 block.py

python block.py

rm block.py

cat P_block.csv T_block.csv F_block.csv > block.csv
rm P_block.csv T_block.csv F_block.csv
#cat P_block.csv T_block.csv U_block.csv > block.csv
#rm P_block.csv T_block.csv U_block.csv
#cat P_block.csv T_block.csv V_block.csv  > block.csv
#rm P_block.csv T_block.csv V_block.csv
#cat P_block.csv T_block.csv U_block.csv TS_block.csv EK_block.csv F_block.csv > block.csv
#rm P_block.csv T_block.csv U_block.csv TS_block.csv EK_block.csv F_block.csv
