#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(31):
	def f(y,x=x[i],T=14000,b0=10.71307,b1=4.52556,v0=3.77845):
		return 1.5*b0*((v0/y)**(7/3)-(v0/y)**(5/3))*(1+0.75*(b1-4)*((v0/y)**(2/3)-1))-x
	y=fsolve(f,0.5)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

