#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(31):
	def f(y,x=x[i],T=14000,b0=25.53597,b1=4.13963,v0=2.88748,c=-7.93966,d=8.16518,e=-0.55875):
		return 1.5*b0*((v0/y)**(7/3)-(v0/y)**(5/3))*(1+0.75*(b1-4)*((v0/y)**(2/3)-1))+(T-8000)/1000*(c+d*(v0/y)+e*(v0/y)**2)-x
	y=fsolve(f,0.5)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

