#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(31):
	def f(y,x=x[i],T=14000,b0=0.57767,b1=3.895,b2=-6.556,v0=13.210,c=1.31807,d=0.469,e=0.01328):
		return 1.5*b0*((v0/y)**(7/3)-(v0/y)**(5/3))*(1+0.75*(b1-4)*((v0/y)**(2/3)-1)+(1/24)*(9*b1**2-63*b1+9*b0*b2+143)*((v0/y)**(2/3)-1)**2)+(T-8000)/1000*(c+d*(v0/y)+e*(v0/y)**2)-x
	y=fsolve(f,0.5)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

