#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(13):
	def f(y,x=x[i],b=-13.282,c=-15.021,T=3500):
    		return b+8.617333*10**(-5)*T*(np.log(x/(6.4-4.4*x))+np.log(1/(6.4-4.4*x)))-c-8.617333*10**(-5)*T*(np.log(y/(5-3*y))+np.log((3-2*y)/(5-3*y)))
	y=fsolve(f,0.00000000001)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

