#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(2):
	#def f(y,x=x[i],b=-4.155091372,c=-3.45563,d=-0.19526,T=3000):
    		#return b-c-d*y-8.617333*10**(-5)*T*np.log(y/(5-4*y))
	def f(y,x=x[i],b=-3.897628819,c=-3.300,T=3000):
                return b-c-8.617333*10**(-5)*T*np.log(y/(5-4*y))
	y=fsolve(f,0.1)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

