#!/usr/bin/env python3

import numpy as np
from scipy.optimize import fsolve

file = open("y.txt", 'w')
x = np.loadtxt("x.txt",skiprows=0,max_rows=None)
for i in range(2):
	def f(y,x=x[i],b=55.571,c=56.252,T=9000):
    		return b+8.617333*10**(-5)*T*(2*np.log(2*x/(6.4-3.4*x))+np.log(1/(6.4-3.4*x)))-c-8.617333*10**(-5)*T*(2*np.log(2*y/(5-2*y))+np.log((3-2*y)/(5-2*y)))
	y=fsolve(f,0.00001)
	convergence=f(y)
	print(y)
	print(convergence)
	np.savetxt(file,np.transpose([y,convergence]))
file.close()

