#!/usr/bin/env python3

import numpy as np
import uncertainties as u
from uncertainties import ufloat

EC = np.array([ufloat(818, 230), ufloat(156.2, 49), ufloat(809.5, 285), ufloat(55.8, 8.4),ufloat(634, 171), ufloat(528.2, 151),ufloat(1124.6, 319), ufloat(285, 99),])
OC = np.array([ufloat(881.6, 324), ufloat(189.5, 63), ufloat(678, 202), ufloat(63.9, 22),ufloat(720, 245), ufloat(577.9, 233),ufloat(1199.8, 451), ufloat(202, 60),])
CC = np.array([ufloat(837.6, 157), ufloat(151.1, 19), ufloat(636.9, 156), ufloat(52.6, 23),ufloat(651.4, 282), ufloat(573.3, 119),ufloat(1119.6, 208), ufloat(156, 30),])
CI = np.array([ufloat(637.4, 18.1), ufloat(131, 5.9), ufloat(570.5, 13.6), ufloat(38.1, 1.9),ufloat(460.5, 4.4), ufloat(430.6, 15.2),ufloat(873.5, 22.6), ufloat(175, 13.5),])

#3500K,computational results
#logDFe_PM = np.array([ufloat(3.673, 0.612), ufloat(3.008, 0.612), ufloat(1.879, 0.612), ufloat(4.459, 0.612),ufloat(4.842, 0.612), ufloat(4.487, 0.612),ufloat(3.420, 0.612), ufloat(2.145, 0.612),])
#logDFeS_PM = np.array([ufloat(4.308, 0.612), ufloat(3.839, 0.612), ufloat(2.917, 0.612), ufloat(4.140, 0.612),ufloat(4.388, 0.612), ufloat(4.063, 0.612),ufloat(3.279, 0.612), ufloat(2.366, 0.613),])

#3000K,based on extrapolation of computational results
#logDFe_PM = np.array([ufloat(4.356, 0.715), ufloat(3.580, 0.715), ufloat(2.262, 0.715), ufloat(5.272, 0.715),ufloat(5.719, 0.715), ufloat(5.306, 0.715),ufloat(4.060, 0.715), ufloat(2.573, 0.715),])
#logDFeS_PM = np.array([ufloat(5.078, 0.715), ufloat(4.532, 0.715), ufloat(3.457, 0.714), ufloat(4.884, 0.714),ufloat(5.173, 0.714), ufloat(4.793, 0.714),ufloat(3.879, 0.715), ufloat(2.813, 0.715),])

#2500K,based on extrapolation of computational results
#logDFe_PM = np.array([ufloat(5.312, 0.857), ufloat(4.380, 0.857), ufloat(2.799, 0.857), ufloat(6.411, 0.857),ufloat(6.947, 0.857), ufloat(6.451, 0.857),ufloat(4.957, 0.857), ufloat(3.172, 0.857),])
#logDFeS_PM = np.array([ufloat(6.158, 0.857), ufloat(5.502, 0.857), ufloat(4.212, 0.857), ufloat(5.924, 0.857),ufloat(6.271, 0.857), ufloat(5.815, 0.857),ufloat(4.718, 0.857), ufloat(3.439, 0.858),])

#3500K,based on fitting results
#logDFe_PM = np.array([ufloat(3.900, 0.660), ufloat(3.307, 0.836), ufloat(1.993, 0.499), ufloat(4.542, 0.374),ufloat(5.199, 1.347), ufloat(4.970, 1.320),ufloat(3.788, 1.006), ufloat(2.130, 0.593),])
#logDFeS_PM = np.array([ufloat(4.037, 0.450), ufloat(3.530, 0.646), ufloat(2.597, 0.898), ufloat(4.042, 0.272),ufloat(4.279, 0.228), ufloat(4.213, 0.582),ufloat(3.318, 0.772), ufloat(2.043, 0.901),])

#3400K,based on fitting results
#logDFe_PM = np.array([ufloat(4.097, 0.669), ufloat(3.523, 0.846), ufloat(2.163, 0.505), ufloat(4.662, 0.379),ufloat(5.370, 1.363), ufloat(5.141, 1.363),ufloat(3.935, 1.019), ufloat(2.224, 0.599),])
#logDFeS_PM = np.array([ufloat(4.097, 0.455), ufloat(3.584, 0.651), ufloat(2.672, 0.907), ufloat(4.072, 0.275),ufloat(4.312, 0.230), ufloat(4.260, 0.589),ufloat(3.382, 0.780), ufloat(2.113, 0.910),])

#3300K,based on fitting results
#logDFe_PM = np.array([ufloat(4.307, 0.677), ufloat(3.753, 0.857), ufloat(2.344, 0.511), ufloat(4.789, 0.383),ufloat(5.551, 1.380), ufloat(5.323, 1.354),ufloat(4.092, 1.032), ufloat(2.325, 0.605),])
#logDFeS_PM = np.array([ufloat(4.161, 0.460), ufloat(3.642, 0.657), ufloat(2.752, 0.917), ufloat(4.104, 0.278),ufloat(4.348, 0.232), ufloat(4.311, 0.595),ufloat(3.450, 0.789), ufloat(2.188, 0.921),])

#3200K,based on fitting results
#logDFe_PM = np.array([ufloat(4.530, 0.687), ufloat(3.996, 0.869), ufloat(2.535, 0.519), ufloat(4.925, 0.389),ufloat(5.743, 1.399), ufloat(5.517, 1.373),ufloat(4.258, 1.046), ufloat(2.431, 0.612),])
#logDFeS_PM = np.array([ufloat(4.229, 0.465), ufloat(3.703, 0.664), ufloat(2.837, 0.928), ufloat(4.138, 0.2782),ufloat(4.385, 0.234), ufloat(4.364, 0.602),ufloat(3.522, 0.798), ufloat(2.267, 0.933),])

#3100K,based on fitting results
#logDFe_PM = np.array([ufloat(4.767, 0.697), ufloat(4.256, 0.882), ufloat(2.739, 0.526), ufloat(5.069, 0.395),ufloat(5.948, 1.419), ufloat(5.723, 1.394),ufloat(4.434, 1.062), ufloat(2.544, 0.619),])
#logDFeS_PM = np.array([ufloat(4.301, 0.471), ufloat(3.768, 0.671), ufloat(2.927, 0.940), ufloat(4.175, 0.285),ufloat(4.425, 0.237), ufloat(4.421, 0.610),ufloat(3.599, 0.809), ufloat(2.352, 0.945),])

#3000K,based on fitting results
#logDFe_PM = np.array([ufloat(5.020, 0.708), ufloat(4.532, 0.896), ufloat(2.957, 0.535), ufloat(5.223, 0.401),ufloat(6.166, 1.441), ufloat(5.942, 1.416),ufloat(4.623, 1.079), ufloat(2.665, 0.627),])
#logDFeS_PM = np.array([ufloat(4.377, 0.478), ufloat(3.838, 0.679), ufloat(3.023, 0.953), ufloat(4.213, 0.289),ufloat(4.468, 0.239), ufloat(4.482, 0.619),ufloat(3.681, 0.820), ufloat(2.442, 0.959),])

#2500K,based on fitting results
logDFe_PM = np.array([ufloat(6.587, 0.781), ufloat(6.247, 0.989), ufloat(4.306, 0.590), ufloat(6.177, 0.442),ufloat(7.519, 1.585), ufloat(7.304, 1.562),ufloat(5.792, 1.190), ufloat(3.413, 0.680),])
logDFeS_PM = np.array([ufloat(4.853, 0.521), ufloat(4.269, 0.730), ufloat(3.620, 1.039), ufloat(4.453, 0.316),ufloat(4.733, 0.258), ufloat(4.859, 0.675),ufloat(4.188, 0.895), ufloat(3.002, 1.048),])

F_sulfide_init = 0.06
F_sulfide_mix = 0.004
LVfraction = 0.003
Corefraction = 0.001

C_HSE_FeS = np.array([ufloat(0, 0), ufloat(0, 0), ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),])
C_HSE_PM = np.array([ufloat(0, 0), ufloat(0, 0), ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),])
C_HSE_Fe = np.array([ufloat(0, 0), ufloat(0, 0), ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),])
C_HSE_FeS_value = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_PM_value = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_Fe_value = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_FeS_error = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_PM_error = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_Fe_error = np.array([0,0,0,0,0,0,0,0],dtype='f')

C_HSE_PM_pred = np.array([ufloat(0, 0), ufloat(0, 0), ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),ufloat(0, 0), ufloat(0, 0),])
C_HSE_PM_pred_value = np.array([0,0,0,0,0,0,0,0],dtype='f')
C_HSE_PM_pred_error = np.array([0,0,0,0,0,0,0,0],dtype='f')

file = open("y.txt", 'w')

#Initial distribution without sulfide segregation
#for i in range(8):
#        C_HSE_Fe[i] = (0.95*EC[i] + 0.05*CC[i]) / (0.323 + 0.677/10**logDFe_PM[i])
#        C_HSE_PM[i] = C_HSE_Fe[i] / 10**logDFe_PM[i]
#        C_HSE_PM_value[i] = C_HSE_PM[i].nominal_value
#        C_HSE_PM_error[i] = C_HSE_PM[i].std_dev
#        C_HSE_Fe_value[i] = C_HSE_Fe[i].nominal_value
#        C_HSE_Fe_error[i] = C_HSE_Fe[i].std_dev
#print(C_HSE_FeS, C_HSE_PM, C_HSE_Fe)


#Initial distribution with sulfide segregation
for i in range(8):
	C_HSE_FeS[i] = (0.95*EC[i] + 0.05*CC[i]) / ((0.323-F_sulfide_init)*10**logDFe_PM[i]/10**logDFeS_PM[i] + F_sulfide_init + 0.677/10**logDFeS_PM[i])
	C_HSE_PM[i] = C_HSE_FeS[i] / 10**logDFeS_PM[i]
	C_HSE_Fe[i] = C_HSE_PM[i] * 10**logDFe_PM[i]
	C_HSE_FeS_value[i] = C_HSE_FeS[i].nominal_value
	C_HSE_FeS_error[i] = C_HSE_FeS[i].std_dev
	C_HSE_PM_value[i] = C_HSE_PM[i].nominal_value
	C_HSE_PM_error[i] = C_HSE_PM[i].std_dev
	C_HSE_Fe_value[i] = C_HSE_Fe[i].nominal_value
	C_HSE_Fe_error[i] = C_HSE_Fe[i].std_dev
print(C_HSE_FeS, C_HSE_PM, C_HSE_Fe)

#no late veneer and core contribution
#for i in range(8):
#	C_HSE_PM_pred[i] = F_sulfide_mix* C_HSE_FeS[i] + (1-F_sulfide_mix)*C_HSE_PM[i]
#	C_HSE_PM_pred_value[i] = C_HSE_PM_pred[i].nominal_value
#	C_HSE_PM_pred_error[i] = C_HSE_PM_pred[i].std_dev
#print("no late veneer and core contribution")
#print(C_HSE_PM_pred)

#with late veneer
#or i in range(8):
#	C_HSE_PM_pred[i] = LVfraction*CC[i] + F_sulfide_mix* C_HSE_FeS[i] + (1-LVfraction-F_sulfide_mix)*C_HSE_PM[i]
#	C_HSE_PM_pred_value[i] = C_HSE_PM_pred[i].nominal_value
#	C_HSE_PM_pred_error[i] = C_HSE_PM_pred[i].std_dev
#print("with late veneer")
#print(C_HSE_PM_pred)

#with core contribution
#for i in range(8):
#	C_HSE_PM_pred[i] = Corefraction*C_HSE_Fe[i] + F_sulfide_mix* C_HSE_FeS[i] + (1-Corefraction-F_sulfide_mix)*C_HSE_PM[i]
#	C_HSE_PM_pred_value[i] = C_HSE_PM_pred[i].nominal_value
#	C_HSE_PM_pred_error[i] = C_HSE_PM_pred[i].std_dev
#print("with core contribution")
#print(C_HSE_PM_pred)

#with late veneer and core contribution
for i in range(8):
	C_HSE_PM_pred[i] = LVfraction*CC[i] + Corefraction*C_HSE_Fe[i] + F_sulfide_mix* C_HSE_FeS[i] + (1-LVfraction-Corefraction-F_sulfide_mix)*C_HSE_PM[i]
	C_HSE_PM_pred_value[i] = C_HSE_PM_pred[i].nominal_value
	C_HSE_PM_pred_error[i] = C_HSE_PM_pred[i].std_dev
print("with late veneer and core contribution")
print(C_HSE_PM_pred)
np.savetxt(file,np.transpose([C_HSE_FeS_value,C_HSE_FeS_error, C_HSE_PM_value, C_HSE_PM_error, C_HSE_Fe_value, C_HSE_Fe_error, C_HSE_PM_pred_value, C_HSE_PM_pred_error]),fmt='%1.3f')
file.close()

